### ISSUE TITLE
I have newbie doubts

### ISSUE THREAD

**Issue by sastreae** [Magisk-Modules-Alt-Repo/chroot-distro#4] opened 2024-03-31 05:46 UTC
![Screenshot_20240331-024519_Termux.jpg](https://github.com/Magisk-Modules-Alt-Repo/chroot-distro/assets/39068642/fdb75576-2496-437a-92fd-27a60684a7f0)

to be able to use the chroot-distro commands. I have to do it from your. and when I do it. It won't let me download the distribution.

**Comment by crypto-the-great** [comment] 2024-07-07 02:21
Interesting, I'm getting the same problem. I can't install any  of the Debian operating systems. All other os'es I have tried have worked, just try using a different os other than debian until it gets fixed8

**Comment by jjkola** [comment] 2024-07-08 21:21
@sastreae what is your device / environment? Also, as I mentioned in #9 based on quick googling it may be issue with too old wget.

@crypto-the-great as the error message is same then it is most likely same issue so there is no need to create a separate issue unless this issue was originally about something else.

**Comment by jjkola** [comment] 2024-07-09 09:58
#3 bug report seems to be of same issue but for some reason the original reporter has closed the issue. I have tried to reach OP to see if he was able to fix it.

**Comment by jjkola** [comment] 2024-07-11 21:10
Duplicate of #3

**Closed** 2024-07-11 21:10 UTC
