### ISSUE TITLE
No internet in any distro

### ISSUE THREAD

**Issue by gitmanbloggus** [Magisk-Modules-Alt-Repo/chroot-distro#46] opened 2024-10-13 19:37 UTC
As soon as I enter into the distro, I don't have internet
How would I fix this

**Comment by jjkola** [comment] 2024-10-13 20:08
Before anything else, can you run `chroot-distro env` and attach the output as an attachment? Also, what distribution are you running, and be as specific as possible? Did you do some setups within the jail?

I'm asking this because chroot doesn't touch or hide anything device related. It is just a way to confine the running program within the file system part specified during chroot invocation.

**Comment by gitmanbloggus** [comment] 2024-10-14 06:30
> Before anything else, can you run `chroot-distro env` and attach the output as an attachment? Also, what distribution are you running, and be as specific as possible? Did you do some setups within the jail?
> 
> I'm asking this because chroot doesn't touch or hide anything device related. It is just a way to confine the running program within the file system part specified during chroot invocation.

1. Arch linux
2. Fresh install 
`Script: /system/bin/chroot-distro
Version: 1.2.1
Versioncode: 9
md5 hash: 50755dd4fa0c5a182d051c7ce6af12a5
Toybox version: toybox 0.8.10-android
busybox => '/system/bin/busybox'
Busybox version: BusyBox v1.36.1-osm0sis (2023-09-02 19:01:41 A
DT) multi-call binary.
chroot => '/system/bin/chroot'
/system/bin/chroot-distro[231]: /data/adb/magisk/magisk64: inac
cessible or not found
Magisk installed ()
Busybox for Android NDK Magisk module installed
Linux 4.14.352-openela-g9072f8dd0764 #1 SMP PREEMPT Thu Oct 10
08:45:34 UTC 2024 aarch64 Android
PATH=/product/bin:/apex/com.android.runtime/bin:/apex/com.andro
id.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/v
endor/bin:/vendor/xbin`

**Comment by gitmanbloggus** [comment] 2024-10-14 06:45
If it helps you: Lineage os 21 on pixel 4a

**Comment by jjkola** [comment] 2024-10-14 20:39
Do you have Magisk installed? Because you have `/data/adb/magisk/` folder but not `magisk64` binary.

If not, then what root solution do you have?

But, back to issue at hand. What is the environment you are using? ADB shell? Termux? Or something else?

Also, if you run `ifconfig` before `chroot-distro login archlinux`, what does it output? What about if you run it inside the jail?

**Comment by gitmanbloggus** [comment] 2024-10-15 03:31
> Do you have Magisk installed? Because you have `/data/adb/magisk/` folder but not `magisk64` binary.
> 
> If not, then what root solution do you have?
> 
> But, back to issue at hand. What is the environment you are using? ADB shell? Termux? Or something else?
> 
> Also, if you run `ifconfig` before `chroot-distro login archlinux`, what does it output? What about if you run it inside the jail?

Magisk is installed...  It's how I got root

**Comment by jjkola** [comment] 2024-10-15 17:46
Regarding, Magisk, can you run `ls -lA /data/adb/magisk` and include the output here? (This is just so that I can add better check for your environment).

To help with your issue, can you tell which command line provider do you use? ADB shell (Android terminal shell), Termux, TWRP, MT Manager? Or, something else?

Also, I'm still waiting for your output from `ifconfig` from the host side as well as from inside the chroot.

**Comment by gitmanbloggus** [comment] 2024-10-15 18:50
> Regarding, Magisk, can you run `ls -lA /data/adb/magisk` and include the output here? (This is just so that I can add better check for your environment).
> 
> To help with your issue, can you tell which command line provider do you use? ADB shell (Android terminal shell), Termux, TWRP, MT Manager? Or, something else?
> 
> Also, I'm still waiting for your output from `ifconfig` from the host side as well as from inside the chroot.

Oh darn
I'm using term1+
For ls -lA /data/adb/magisk: it returns magisk's files 
total 3531
-rwxr-xr-x 1 root root    4034 2024-10-12 17:32 addon.d.sh
-rwxr-xr-x 1 root root    6943 2024-10-12 17:32 boot_patch.sh
-rwxr-xr-x 1 root root 1710600 2024-10-12 17:32 busybox
drwxr-xr-x 2 root root    3452 2024-10-12 17:32 chromeos
-rwxr-xr-x 1 root root    5040 2024-10-12 17:32 init-ld
-rwxr-xr-x 1 root root  310232 2024-10-12 17:32 magisk
-rwxr-xr-x 1 root root  200940 2024-10-12 17:32 magisk32
-rwxr-xr-x 1 root root  770688 2024-10-12 17:32 magiskboot
-rwxr-xr-x 1 root root  188584 2024-10-12 17:32 magiskinit
-rwxr-xr-x 1 root root  340008 2024-10-12 17:32 magiskpolicy
-rwxr-xr-x 1 root root   29053 2024-10-12 17:32 stub.apk
-rwxr-xr-x 1 root root   19889 2024-10-12 17:32 util_function

**Comment by gitmanbloggus** [comment] 2024-10-15 20:10
> Regarding, Magisk, can you run `ls -lA /data/adb/magisk` and include the output here? (This is just so that I can add better check for your environment).
> 
> To help with your issue, can you tell which command line provider do you use? ADB shell (Android terminal shell), Termux, TWRP, MT Manager? Or, something else?
> 
> Also, I'm still waiting for your output from `ifconfig` from the host side as well as from inside the chroot.

Ifconfig:
![Screenshot_20241015-160927_Terminal Emulator](https://github.com/user-attachments/assets/19495e1a-31fe-48e9-a475-2d6380c4031e)

**Comment by jjkola** [comment] 2024-10-15 20:18
Does `ifconfig` have same output from inside the chroot? I mean after running `chroot-distro login archlinux`.

**Comment by gitmanbloggus** [comment] 2024-10-15 20:20
> Does `ifconfig` have same output from inside the chroot? I mean after running `chroot-distro login archlinux`.

![Screenshot_20241015-162010_Terminal Emulator](https://github.com/user-attachments/assets/e9f913ef-946e-46c5-9af1-c67a84e09862)

**Comment by jjkola** [comment] 2024-10-15 21:01
It would have been easier to compare those if the ouput was in text format, but based on those images, it seems that when within archlinux the wlan0 seems to have an address but not in the outside. If the packet routing is wrong because of that then that would explain why there is no internet.

I think the next step would be to check routing before going to the chroot, and then within chroot. If they differ then you will most likely have found the culprit, and only need to find out why this happens. If the routing is the same then the issue is more hairy, and unfortunately most likely I will not be able to help you.

And, just for completeness, after exiting the chroot, does the internet connection start working again?

**Comment by gitmanbloggus** [comment] 2024-10-16 01:32
> It would have been easier to compare those if the ouput was in text format, but based on those images, it seems that when within archlinux the wlan0 seems to have an address but not in the outside. If the packet routing is wrong because of that then that would explain why there is no internet.
> 
> I think the next step would be to check routing before going to the chroot, and then within chroot. If they differ then you will most likely have found the culprit, and only need to find out why this happens. If the routing is the same then the issue is more hairy, and unfortunately most likely I will not be able to help you.
> 
> And, just for completeness, after exiting the chroot, does the internet connection start working again?

Internet in android works fine inside and outside the chroot
Seems to be a problem with address assigning

**Comment by jjkola** [comment] 2024-10-16 05:13
Since the issue is no more related to `chroot-distro` I will close this issue as soon as the fix for the Magisk version detection (#47) lands.

**Comment by gitmanbloggus** [comment] 2024-10-17 14:30
> Since the issue is no more related to `chroot-distro` I will close this issue as soon as the fix for the Magisk version detection (#47) lands.

Got it, thank you

**Closed** 2024-10-17 14:29 UTC
