### ISSUE TITLE
Inaccessible userdata after using chroot-distro

### ISSUE THREAD

**Issue by nickelberg** [Magisk-Modules-Alt-Repo/chroot-distro#33] opened 2024-09-03 20:21 UTC
I can't be the only one, so it should be pretty self explanatory.
Happened on two my different phones - common features: Xiaomi, rooted, Android 14.
After exiting shell from distro's chroot and then exiting Termux, phone apps don't have access to phone storage.

Examples:
- **Gallery** not able to display photos
- **Files** (app) not able to display internal memory files
- **Material Files**, here I got more informative error message:
"java8.nio.file.FileSystemException: /storage/emulated/0: opendir: Transport endpoint is not connected"

Edit:
Important to add - a simple reboot fixes this, but it's cumbersome.

**Comment by jjkola** [comment] 2024-09-07 19:21
Thanks for the report and the extra information. I did notice your bug report a few days ago. Unfortunately, I have been really busy, so I haven't been able to react to your report.

Just using chroot should not cause this kind of behavior. Also, as `chroot-distro` uses bind mounts, it should not cause the described behavior.

So, I would like to have more information about the situation so that I can try to reproduce the issue.

First, what distribution did you use? Be as exact as possible.

Second, while using the distribution, what did you do? If you can provide clear steps to reproduce the issue, then all the better.

Third, after exiting the jail, did you just close the Termux, or did you issue some commands?

**Comment by nickelberg** [comment] 2024-09-10 18:41
1. Debian 12 and Alpine 3.19
2. Doesn't matter. I can install whole desktop enviroment and vnc server or just do sudo apt update and then quit. It will happen anyway.
3. Steps:
3.1 chroot-distro:$ exit
3.2 Termux#: chroot-distro unmount debian
3.3 Termux#: exit
3.4 Termux$: exit
3.5 \*app closes*
4. It has happened every time I used chroot-distro. Originally in March 16th version and even in the most recent version v1.1.3.

And most importantly I forgot to add:
I'm not using Magisk, I have KernelSU on both of my phones.
There's a high possibility, this is the bug culprit.

**Comment by jjkola** [comment] 2024-09-15 16:54
Unfortunately I don't have any devices with KernelSU so I can't test this. @YasserNull, do you have any devices with KernelSU?

**Comment by YasserNull** [comment] 2024-09-16 18:43
No, I don't have any devices with KernelSU.

**Comment by roninspin** [comment] 2024-09-16 22:25
`chroot-distro unmount <distro>` (ubuntu in my case) really unmounts /storage/* for android instead of chroot distro. Maybe `chroot_distro_unmount_system_points` receives empty `distro_path` somehow.
Btw. I have KernelSU and I use `chroot-distro` as a standalone script (without installed module).

**Comment by defectly** [comment] 2024-09-20 05:31
it's not kernelSU problem i guess, i've been using tmoe for chroots, and there's same problem with unmount

**Comment by jjkola** [comment] 2024-09-21 10:21
I have checked, and `distro_path` should not be empty. @nickelberg, @roninspin and @defectly, can you run `command -v umount` and then with the path run `ls -l <path returned by command>`. I want to check what is providing the umount command. These needs to be run as a root, and I want the output of both commands.

**Comment by defectly** [comment] 2024-09-21 10:24
> I have checked, and `distro_path` should not be empty. @nickelberg, @roninspin and @defectly, can you run `command -v umount` and then with the path run `ls -l <path returned by command>`. I want to check what is providing the umount command. These needs to be run as a root, and I want the output of both commands.

like this? 
![Screenshot_20240921-132423_Termux](https://github.com/user-attachments/assets/1dd9bb61-63bc-4ad5-8d71-231cc9a63cb5)

**Comment by jjkola** [comment] 2024-09-21 10:53
@defectly thanks, that was what I wanted to see

@roninspin Using standalone version of `chroot-distro` is not a problem, only matter of convenience and preference. If you want, you can run `mksh -xv <location of chroot-distro> unmount <distro>` after normal login, and redirect the output to a file. The output will tell exactly what commands were run, and with what parameters. If you don't mind would you like to share the output for example through pastebin (or some similar service) if you did run the debug run?

**Comment by roninspin** [comment] 2024-09-21 14:50
> @roninspin Using standalone version of `chroot-distro` is not a problem, only matter of convenience and preference. If you want, you can run `mksh -xv <location of chroot-distro> unmount <distro>` after normal login, and redirect the output to a file. The output will tell exactly what commands were run, and with what parameters. If you don't mind would you like to share the output for example through pastebin (or some similar service) if you did run the debug run?

Here you go
https://pastebin.com/MNdaLxJw

**Comment by jjkola** [comment] 2024-09-22 08:54
Based on debug log, the script has worked as it should. I'm starting to think that there may be a problem with toybox implementation of umount in this particular situation, or something else which affects umount calls.

@nickelberg, @roninspin and @defectly: Can you provide as much information about your device as possible? At least device model, android version, firmware version, twrp version (just in case, or if you didn't install twrp, then what did you install, or if you didn't install custom recovery at all), kernel version, busybox version (should not matter but does no harm). Also, can you guys run `toybox --version`? Also, if you have custom rom, then what rom, and what version?

**Comment by defectly** [comment] 2024-09-22 09:31
> Based on debug log, the script has worked as it should. I'm starting to think that there may be a problem with toybox implementation of umount in this particular situation, or something else which affects umount calls.
> 
> @nickelberg, @roninspin and @defectly: Can you provide as much information about your device as possible?
> 
> At least device model, android version, firmware version, twrp version (or if you didn't install twrp, then what did you install, or if you didn't install custom recovery at all), kernel version, busybox version (should not matter but does no harm).
> 
> Also, can you guys run `toybox --version`? Also, if you have custom rom, then what rom, and what version? Also, just in case, whether the device has kernelsu or magisk, and what is the version?
> 
> One more thing, can you run `mount` (and redirect the output to file) before distro login, and after exiting the distro but before `unmount` command, and lastly after `unmount`, just so that it is easier to see what happens to mounts. And if you could attach the outputs to your reply (one reply per device)?

Xiaomi Redmi Note 10 Pro
model: M2101K6G
codename: sweet
Android 13 Cherish OS 4.8 (custom)
PitchBlack Recovery Project 4.0
KernelSU version 11872

![Screenshot_20240922-120936_Settings](https://github.com/user-attachments/assets/68c8b051-3ca0-4915-9c02-a532e6f5020f)

![Screenshot_20240922-120936_Settings](https://github.com/user-attachments/assets/d46f79e5-27c4-4a90-adb1-e7af981a0ac9)

[mount.txt](https://github.com/user-attachments/files/17088964/mount.txt)
[mount2.txt](https://github.com/user-attachments/files/17088993/mount2.txt)
[mount3.txt](https://github.com/user-attachments/files/17088995/mount3.txt)

**Comment by jjkola** [comment] 2024-09-22 11:41
If somebody could also provide their device information if this is working properly, then that may help providing direction to where this bug may lay. Based on the mount data from @defectly, it should work without problems, but clearly it isn't. I checked toybox change logs from news page and the last time umount command was changed is for version 0.8.0, and the change was to ignore -c parameter. So, most likely toybox is not the cause for the bug unless it is a bug which has been there always/very long time.

P.S. @nickelberg and @roninspin, I would still like to get the device information from you guys, so that we have more data available to help pinpoint where the problem lays.

**Comment by roninspin** [comment] 2024-09-22 13:07
Nubia Red Magic 6 (NX669J)
ROM: stock android 12(L)
kernel: 5.4.249 (lots of backports)
TWRP 3.7.0
KernelSU: 11928
toybox: 0.8.4-android
BusyBox for Android NDK version 1.36.1

Turns out that the reason of the problem (at least for me) is the use of umount with -f (forced) for <distro>/storage/emulated. Without that parameter no problems at all.

**Comment by jjkola** [comment] 2024-09-22 16:44
@roninspin Thanks, good catch. We will have to investigate this but it sounds like something has changed on kernel side which makes it unusable on newer kernels (my device is Asus Zenpad 10 (Z301M) with 3.18.35 kernel, and it works). Bind mounts should never affect their originator mounts but clearly this has been broken at some point.

@YasserNull Do you happen to remember why -f flag has been added?

**Comment by nickelberg** [comment] 2024-09-22 17:31
Sorry for not much response from me, I'm kinda busy irl lately.
***
@jjkola
## Phone 1:

- **Phone:** Xiaomi Mi 9T Pro (codename raphael)
- **ROM:** Android 14 - LineageOS 21 (Unofficial build)
- **Kernel:** 4.14.350
- **Recovery:** OrangeFox R11.1_4 Stable
- **KernelSU:** 11872
- **Toybox:** 0.8.10-android
- **BusyBox:** 1.36.1

## Phone 2:

- **Phone:** POCO F4 GT (codename ingres)
- **ROM:** Android 14 - HyperOS 1.0.4.0.ULJCNXM (xiaomi.eu)
- **Kernel:** 5.10.192
- **Recovery:** OrangeFox R12.1_1 Unofficial
- **KernelSU:** 11928
- **Toybox:** 0.8.9-android
- **BusyBox:** 1.36.1

**Comment by YasserNull** [comment] 2024-09-22 17:38
@jjkola In fact, I don't remember, but what I do remember is that I used ChatGPT to learn how to use this command.

**Comment by jjkola** [comment] 2024-09-22 18:43
I did a test on my raspi device where I did multiple successive bind mounts, and forced unmount (-lf) worked properly with kernel 6.6.47.

**Comment by roninspin** [comment] 2024-09-22 19:31
Anyway, -f shouldn't be used all the time (by default).

**Comment by jjkola** [comment] 2024-09-29 09:02
Fix released.

**Comment by defectly** [comment] 2024-09-29 10:16
> Fix released.

![Screenshot_20240929-131531_Termux](https://github.com/user-attachments/assets/6cb15783-755e-4ee1-8f3b-e0acf456acd5)

so how do i shutdown it?

**Comment by jjkola** [comment] 2024-09-29 21:18
I'll try to add more output to error message to make it easier to pinpoint the problem. Most likely I will have time for that next weekend.

**Comment by jjkola** [comment] 2024-09-30 14:49
In the mean time, you can try following:
`mount | grep <mount_point_path>`
`losetup | grep <mount_point_path>`
`lsof | grep <mount_point_path>`

If those don't help (and there is no running processes) then you will have to check for anonymous inodes and inotify watchers.

**Comment by defectly** [comment] 2024-09-30 15:30
> In the mean time, you can try following: `mount | grep <mount_point_path>` `losetup | grep <mount_point_path>` `lsof | grep <mount_point_path>`
> 
> If those don't help (and there is no running processes) then you will have to check for anonymous inodes and inotify watchers.

can it be automatic? tmoe has feature to kill chroot, and it also kills chroot if you use unmount in it

**Comment by jjkola** [comment] 2024-10-01 16:29
Sure, it can be added. But it can't be default action as it can leave the jail in inconsistent state as it will not bring it down in managed/consistent way. At least, I would prefer bringing my stuff down in a way that it will not cause problems for me in the future.

Also, just to be clear the `unmount` command just unmounts the known system mount points, it does nothing more, nothing less.

**Comment by jjkola** [comment] 2024-11-10 15:24
I have now a PR to add `force` option to `unmount` and `uninstall` commands. Sorry, that it took time to create this PR. I have had the code ready for some time but wanted to do final test round for it, but unfortunately I have been quite busy IRL.

**Comment by jjkola** [comment] 2024-11-12 18:19
@defectly Do you have a chance to test my changes from PR? Since you had problems with storage mounts it would be nice to get some input how the new PR is doing. Also, it would be nice if you could include the output here (if the `unmount`/`uninstall` command does not run successfully without `force` option).

**Comment by defectly** [comment] 2024-11-12 18:43
> @defectly Do you have a chance to test my changes from PR? Since you had problems with `storage` mounts it would be nice to get some input how the new PR is doing. Also, it would be nice if you could include the output here (if the `unmount`/`uninstall` command does not run successfully without `force` option).

maybe if you give instructions

**Comment by jjkola** [comment] 2024-11-12 22:01
Just download the code (either as a zip, or with git) from the PR by going to the branch in my repo. Then create development version of the `chroot-distro` with the help of hacking guide from README. After installing the package and rebooting the device, just use normally as you would. I'm mostly interested in the output of `unmount` command (or `uninstall` if you can test that also).

**Comment by defectly** [comment] 2024-11-12 23:16
> Just download the code (either as a zip, or with git) from the PR by going to the branch in my repo. Then create development version of the `chroot-distro` with the help of hacking guide from README. After installing the package and rebooting the device, just use normally as you would. I'm mostly interested in the output of `unmount` command (or `uninstall` if you can test that also).

so, in first case i tried unmount with ubuntu
when it says device or resource busy, it takes terminal i/o until i press ctrl + c
and it doesn't affect running ubuntu

```
:/ # chroot-distro unmount ubuntu
umount: /data/local/chroot-distro/ubuntu/storage/emulated: Device or resource busy

^C
130|:/ # chroot-distro unmount
chroot-distro - misssing distro
try 'chroot-distro help' for more information
2|:/ # chroot-distro help
chroot-distro : install linux distributions

usage :

chroot-distro help - for more information
chroot-distro env - output debug information about environment
chroot-distro list - list of available linux distributions

chroot-distro download <distro> - download rootfs
chroot-distro redownload <distro> - redownload rootfs
chroot-distro delete <distro> - delete rootfs

chroot-distro install <distro> [-a|--android] - install distro
    '-a|--android'  Installs also /data and /system folders, by default not installed
chroot-distro reinstall <distro> [-a|--android] [-f|--force] - reinstall distro
    '-a|--android'  Installs also /data and /system folders, by default not installed
    '-f|--force'    Force closing open files (closes the process accessing them)
                    and/or unmounting active mounts. Use with care.
chroot-distro uninstall <distro> [-f|--force] - uninstall distro
    '-f|--force'    Force closing open files (closes the process accessing them)
                    and/or unmounting active mounts. Use with care.

chroot-distro unmount <distro> [-f|--force] [-a|--all] - unmount (system) mount points from distro
    '-f|--force'    Force closing open files (closes the process accessing them)
                    and/or unmounting active mounts which prevents (system) mount points
                    from unmounting. Use with care.
    '-a|--all'      Instead of unmounting only system mount points, will try to unmount
                    all found mount points, be it a normal mount point or a loopback mount point.

chroot-distro backup <distro> [<path>] - backup distro
    <path>          Custom path for backup location
chroot-distro restore <distro> [-d|--default] [--force] [<path>] - restore distro
    <path>          Custom path for backup location
    '-d|--default'  restore default settings (note: only those set during install)
    '--force'       Force restore even if may cause unintended side-effects
chroot-distro unbackup <distro> - delete backup from default location

chroot-distro command <distro> <command> - run command
chroot-distro login <distro> - login to distro

:/ # chroot-distro unmount -f ubuntu
umount: /data/local/chroot-distro/ubuntu/storage/emulated: Device or resource busy
```

in second case i tried unmount and uninstall with debian because i dont want delete ubuntu
and it doesn't affect distro too

```
:/ # chroot-distro unmount debian
:/ # chroot-distro uninstall debian
distro is potentially running - if needed shutdown the distro, and unmount mounted folders

You can try running uninstall again with -f(--force) option to automatically close/unmount files/folders mentioned below.
Please note, that using --force option may close more programs than intended, so use it with care.

open files under /data/local/chroot-distro/debian:
12001   /data/local/chroot-distro/debian/usr/bin/su    0/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    1/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  0/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  1/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  255      /dev/pts/1
end of open files

mount points under /data/local/chroot-distro/debian:
Not found
end of mount points

loopback devices under /data/local/chroot-distro/debian:
Not found
end of loopback devices

If there is no open files, mount points (outside of system mount points) or loopback devices,
then check for anonymous inodes and inotify watches
1|:/ # chroot-distro uninstall -f debian
distro is potentially running - if needed shutdown the distro, and unmount mounted folders

You can try running uninstall again with -f(--force) option to automatically close/unmount files/folders mentioned below.
Please note, that using --force option may close more programs than intended, so use it with care.

open files under /data/local/chroot-distro/debian:
12001   /data/local/chroot-distro/debian/usr/bin/su    0/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    1/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  0/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  1/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  255      /dev/pts/1
end of open files

mount points under /data/local/chroot-distro/debian:
Not found
end of mount points

loopback devices under /data/local/chroot-distro/debian:
Not found
end of loopback devices

If there is no open files, mount points (outside of system mount points) or loopback devices,
then check for anonymous inodes and inotify watches
1|:/ # chroot-distro unmount -f debian
1|:/ # chroot-distro uninstall -f debian
distro is potentially running - if needed shutdown the distro, and unmount mounted folders

You can try running uninstall again with -f(--force) option to automatically close/unmount files/folders mentioned below.
Please note, that using --force option may close more programs than intended, so use it with care.

open files under /data/local/chroot-distro/debian:
12001   /data/local/chroot-distro/debian/usr/bin/su    0/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    1/dev/pts/1
12001   /data/local/chroot-distro/debian/usr/bin/su    2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  0/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  1/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  2/dev/pts/1
12002   /data/local/chroot-distro/debian/usr/bin/bash  255      /dev/pts/1
end of open files

mount points under /data/local/chroot-distro/debian:
Not found
end of mount points

loopback devices under /data/local/chroot-distro/debian:
Not found
end of loopback devices

If there is no open files, mount points (outside of system mount points) or loopback devices,
then check for anonymous inodes and inotify watches
1|:/ #
```

**Comment by jjkola** [comment] 2024-11-13 16:55
Thanks. I'm interested in knowing what is happening with that Ubuntu unmount. Can you run `sh -xv chroot-distro unmount ubuntu > debug.log 2>&1`, and attach the debug file here? I want to ensure that it isn't a bug in the `chroot-distro` implementation.

**Comment by jjkola** [comment] 2024-11-13 18:45
Sorry, I wasn't in front of my computer and remembered the invocation incorrectly. The correct one is: `/bin/sh -xv /system/xbin/chroot-distro unmount ubuntu > debug.log 2>&1`

**Comment by jjkola** [comment] 2024-11-13 19:13
Hmm, wierd. I have /system/bin/sh (this one is mksh) and /bin/sh (and this one is ash, at least based on [whatshell.sh](https://www.in-ulm.de/~mascheck/various/whatshell/whatshell.sh)). Can you run /bin/sh and from within that shell run that script? I would like to know what it is. Also, what does `command -v sh` say?

**Comment by defectly** [comment] 2024-11-13 20:24
> Hmm, that's wierd. I have /system/bin/sh (this one is mksh) and /bin/sh (and this one is ash, at least based on [whatshell.sh](https://www.in-ulm.de/~mascheck/various/whatshell/whatshell.sh)). Can you run `/bin/sh` and from within that shell run that script? I would like to know what it is. Also, what does `command -v sh` say? And, just for posterity, can you run `/system/bin/sh` just for posterity?
> 
> Also, if you can include the output from `chroot-distro env`?

/system/bin/sh returns nothing

command -v sh returns "/system/bin/sh"
 and maybe i wrote command wrong because now it writes this to file
```
/system/bin/sh: /system/xbin/chroot-distro: No such file or directory
```
and same does
```
 /bin/sh -xv /system/xbin/chroot-distro unmount ubuntu > debug.log 2>&1
```

**Comment by jjkola** [comment] 2024-11-13 21:16
Did you accidentally drop the first row that contains the script location? You need to use the same location for `sh` invocation.

**Comment by jjkola** [comment] 2024-11-13 22:15
Thanks, and I forgot that the script is installed at /system/bin directory. Just after you posted your latest output I checked my own device only to find out that you had already found the correct location. There is some fishy going on based on debug output. I will have to debug it. Unfortunately, I'm not sure when I will have time for that, but I will do it as soon as possible.

**Comment by jjkola** [comment] 2024-11-17 22:24
I'll close this after the investigation.

**Comment by jjkola** [comment] 2024-11-27 16:18
I will close this issue as there is already a new issue created about the last issue. I accidentally forgot that there is the looping issue, and created a new version (but then again with the way versioning is handled, some people may have already gotten the non-working version). Looping issue will be tracked with #55.

**Closed by jjkola** 2024-11-27 16:18 UTC
