### ISSUE TITLE
Add Update.json for Auto Updates

### ISSUE THREAD

**Issue by hopez13** [Magisk-Modules-Alt-Repo/chroot-distro#40] opened 2024-09-29 03:54 UTC
it automatically displays update button in module manager when new module version is available 

here's reference implementation 
https://github.com/chiteroman/PlayIntegrityFix/blob/main/update.json

**Comment by jjkola** [comment] 2024-09-29 09:13
Duplicate of #19.

Thanks for the feature request but this has already been added to issue tracker.

**Closed by jjkola** 2024-09-29 09:13 UTC
